apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-web
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
